[env]
TERM = "xterm-256color"

[window]
# padding.x = 0
# padding.y = 15
dimensions.columns = 120
dimensions.lines = 30


decorations = "buttonless"

opacity = 0.95
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 18

[cursor]
style.blinking = "On"
style.shape = "Beam"
