cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'gh'
brew 'ripgrep'
brew 'eza'
brew 'uv'
brew 'tree'
brew 'wget'
brew 'stow'
brew 'gh'
brew 'starship'
brew 'fd'
brew 'gnupg'
brew 'neovim'
brew 'zsh-autosuggestions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'

cask 'appcleaner'
cask 'firefox@nightly'
cask 'fork'
cask 'iina'
cask 'obsidian'
cask 'signal'
cask 'iterm2'
cask 'protonvpn'
cask 'font-jetbrains-mono-nerd-font'


